[package]
name = "csv_to_json_worker"
version = "0.1.0"
edition = "2021"

[dependencies]
csv = "1.2"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
crossbeam = "0.8"
anyhow = "1.0.100"
